variables:
  DOCKER_DRIVER: overlay2

stages:
- build

before_script:
    - rm -fr build SOURCES RPMS

centos6:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/centos6:latest
  stage: build
  tags:
    - moonshot
  script:
    - sed -i "s/\(.\)%{?dist}/\1b$CI_PIPELINE_ID%{?dist}/g" mech_eap.spec.in
    - "for i in ui libradsec; do curl -L -H \"PRIVATE-TOKEN: $TOKEN\" https://gitlab.ci.ti.ja.net/moonshot/$i/-/jobs/artifacts/develop/download?job=centos6 -o deps.zip; unzip deps.zip; done"
    - yum -y install RPMS/x86_64/*.rpm
    - rm -fr RPMS deps.zip
    - sh autogen.sh
    - ./configure
    - make dist
    - mkdir SOURCES
    - mv mech_eap-1.0.1.tar.gz SOURCES
    - rpmbuild -bb mech_eap.spec --define "_topdir `pwd`"
  artifacts:
    paths:
        - RPMS

centos7:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/centos7:latest
  stage: build
  tags:
    - moonshot
  script:
    - sed -i "s/\(.\)%{?dist}/\1b$CI_PIPELINE_ID%{?dist}/g" mech_eap.spec.in
    - "for i in ui libradsec; do curl -L -H \"PRIVATE-TOKEN: $TOKEN\" https://gitlab.ci.ti.ja.net/moonshot/$i/-/jobs/artifacts/develop/download?job=centos7 -o deps.zip; unzip deps.zip; done"
    - yum -y install RPMS/x86_64/*.rpm
    - rm -fr RPMS deps.zip
    - sh autogen.sh
    - ./configure
    - make dist
    - mkdir SOURCES
    - mv mech_eap-1.0.1.tar.gz SOURCES
    - rpmbuild -bb mech_eap.spec --define "_topdir `pwd`"
  artifacts:
    paths:
        - RPMS

debian8:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/debian8:latest
  stage: build
  tags:
    - moonshot
  script:
    - dch -l "b$CI_PIPELINE_ID" "Include job ID"
    - "curl -L -H \"PRIVATE-TOKEN: $TOKEN\" https://gitlab.ci.ti.ja.net/moonshot/ui/-/jobs/artifacts/develop/download?job=debian8 -o deps.zip"
    - unzip deps.zip
    - "dpkg -i build/*.deb || true"
    - apt-get install -fy
    - rm -fr build deps.zip
    - autoreconf -fi
    - ./configure
    - make dist
    - mv mech_eap-1.0.1.tar.gz ../moonshot-gss-eap_1.0.1.orig.tar.gz
    - debuild -us -uc
    - mkdir build
    - cp ../*.deb build
  artifacts:
    paths:
        - build/*.deb

debian9:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/debian9:latest
  stage: build
  tags:
    - moonshot
  script:
    - dch -l "b$CI_PIPELINE_ID" "Include job ID"
    - "curl -L -H \"PRIVATE-TOKEN: $TOKEN\" https://gitlab.ci.ti.ja.net/moonshot/ui/-/jobs/artifacts/develop/download?job=debian9 -o deps.zip"
    - unzip deps.zip
    - "dpkg -i build/*.deb || true"
    - apt-get install -fy
    - rm -fr build deps.zip
    - sh autogen.sh
    - ./configure
    - make dist
    - mv mech_eap-1.0.1.tar.gz ../moonshot-gss-eap_1.0.1.orig.tar.gz
    - debuild -us -uc
    - mkdir build
    - cp ../*.deb build
    # Now, rebuild libevent-openssl with ssl1.0
    - echo "deb-src http://deb.debian.org/debian stretch main" >> /etc/apt/sources.list
    - apt-get update
    - useradd tmpuser
    - su tmpuser -c "apt-get source libevent"
    - cd libevent-2.0.21-stable
    - sed -i 's/libssl/libssl1.0/g' debian/control
    - dch -l moonshot "Build with OpenSSL 1.0"
    - debuild -us -uc
    - cp ../*.deb ../build
  artifacts:
    paths:
        - build/*.deb


ubuntu14:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/ubuntu14:latest
  stage: build
  tags:
    - moonshot
  script:
    - dch -l "b$CI_PIPELINE_ID" "Include job ID"
    - "curl -L -H \"PRIVATE-TOKEN: $TOKEN\" https://gitlab.ci.ti.ja.net/moonshot/ui/-/jobs/artifacts/develop/download?job=ubuntu14 -o deps.zip"
    - unzip deps.zip
    - "dpkg -i build/*.deb || true"
    - apt-get install -fy
    - rm -fr build deps.zip
    - autoreconf -fi
    - ./configure
    - make dist
    - mv mech_eap-1.0.1.tar.gz ../moonshot-gss-eap_1.0.1.orig.tar.gz
    - debuild -us -uc
    - mkdir build
    - cp ../*.deb build
  artifacts:
    paths:
        - build/*.deb

ubuntu16:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/ubuntu16:latest
  stage: build
  tags:
    - moonshot
  script:
    - dch -l "b$CI_PIPELINE_ID" "Include job ID"
    - "curl -L -H \"PRIVATE-TOKEN: $TOKEN\" https://gitlab.ci.ti.ja.net/moonshot/ui/-/jobs/artifacts/develop/download?job=ubuntu16 -o deps.zip"
    - unzip deps.zip
    - "dpkg -i build/*.deb || true"
    - apt-get install -fy
    - rm -fr build deps.zip
    - autoreconf -fi
    - ./configure
    - make dist
    - mv mech_eap-1.0.1.tar.gz ../moonshot-gss-eap_1.0.1.orig.tar.gz
    - debuild -us -uc
    - mkdir build
    - cp ../*.deb build
  artifacts:
    paths:
        - build/*.deb

ubuntu18:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/ubuntu18:latest
  stage: build
  tags:
    - moonshot
  script:
    - dch -l "b$CI_PIPELINE_ID" "Include job ID"
    - "wget --header \"PRIVATE-TOKEN: $TOKEN\" https://gitlab.ci.ti.ja.net/moonshot/ui/-/jobs/artifacts/develop/download?job=ubuntu18 -O deps.zip"
    - unzip deps.zip
    - "dpkg -i build/*.deb || true"
    - apt-get install -fy
    - rm -fr build deps.zip
    - autoreconf -fi
    - ./configure
    - make dist
    - mv mech_eap-1.0.1.tar.gz ../moonshot-gss-eap_1.0.1.orig.tar.gz
    - debuild -us -uc
    - mkdir build
    - cp ../*.deb build
    # Now, rebuild libevent-openssl with ssl1.0
    - echo "deb-src http://archive.ubuntu.com/ubuntu/ bionic main restricted" >> /etc/apt/sources.list
    - apt-get update
    - useradd tmpuser
    - mkdir tmp
    - chown tmpuser tmp
    - cd tmp
    - su tmpuser -c "apt-get source libevent"
    - cd libevent-2.1.8-stable
    - sed -i 's/libssl-dev/libssl1.0-dev/g' debian/control
    - dch -l moonshot "Build with OpenSSL 1.0"
    - debuild -us -uc
    - cp ../*.deb ../../build
  artifacts:
    paths:
        - build/*.deb
