language: c

#compiler: clang

before_install:
 - sudo apt-get install libsaml2-dev libshibsp-dev libkrb5-dev libssl-dev libjansson-dev libcurl4-openssl-dev autoconf automake
 - sh autogen.sh

script: ./configure --enable-gss-mech && make

notifications:
  email:
    - lukeh@padl.com
